# Generated by Django 4.0.3 on 2022-03-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200517_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date', '-time')},
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
