# Generated by Django 4.0.3 on 2022-03-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_options_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_desc',
            field=models.CharField(default=True, max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_tag',
            field=models.CharField(default=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Publish')], max_length=1),
        ),
    ]
