# Generated by Django 4.0.3 on 2022-03-22 17:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_img_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content3',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_desc',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_tag',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Publish')], max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
